<%@ Page Title="" Language="C#" MasterPageFile="~/Admin/Index.Master" AutoEventWireup="true" CodeBehind="Category.aspx.cs" Inherits="ExpenseTracker.Admin.Category" %>

<%--<asp:Content ID="Category" ContentPlaceHolderID="Admin1" runat="server">
    <asp:Label ID="cat1" runat="server" Text="Expense Categories"></asp:Label>
    <asp:GridView
        ID="cat2"
        runat="server"
        CssClass="grid"
        AutoGenerateColumns="true"
        ShowHeaderWhenEmpty="true"
        EmptyDataText="No record found"
        CellPadding="5"
        BorderWidth="1"
        DataKeyNames="category_id"
        AutoGenerateEditButton="true"
        AutoGenerateDeleteButton="true"
        OnRowCancelingEdit="cat_canceledit"
        OnRowEditing="cat_rowedit"
        OnRowUpdating="cat_rowupdate"
        OnRowDeleting="cat_delete"
        GridLines="None" 
        UseAccessibleHeader="true">
    </asp:GridView>




    <div class="category-card">
        <div class="category-header">
            <h2>Expense Tracker</h2>
            <p class="mb-0">Add a new expense category</p>
        </div>
        <div class="form-floating">
            <asp:Label ID="lnm" runat="server" Text="Name" CssClass="form-label"></asp:Label>
            <asp:TextBox ID="nm" runat="server" CssClass="form-control"></asp:TextBox>
            <asp:Button ID="add" runat="server" Text="Add" OnClick="Add_Category" CssClass="btn-add" />
            <asp:Label ID="show" runat="server"></asp:Label>
        </div>
    </div>
    <div class="container">
    </div>
</asp:Content>--%>

<asp:Content ID="Category" ContentPlaceHolderID="Admin1" runat="server">
    <asp:Label ID="cat1" runat="server" Text="Expense Categories"></asp:Label>
    
    <div class="main-layout">
        <div class="grid-container">
            <asp:GridView
                ID="cat2"
                runat="server"
                CssClass="grid"
                AutoGenerateColumns="false"
                ShowHeaderWhenEmpty="true"
                EmptyDataText="No record found"
                CellPadding="5"
                BorderWidth="1"
                DataKeyNames="category_id"
               
                OnRowCancelingEdit="cat_canceledit"
                OnRowEditing="cat_rowedit"
                OnRowUpdating="cat_rowupdate"
                OnRowDeleting="cat_delete"
                GridLines="None" 
                UseAccessibleHeader="true">

                     <Columns>
    <asp:BoundField DataField="category_id" HeaderText="Category ID" />
    <asp:BoundField DataField="name" HeaderText="Name" />
    <asp:BoundField DataField="user_id" HeaderText="User ID" />
         <asp:BoundField DataField="status" HeaderText="Status" />
         <asp:BoundField DataField="created_at" HeaderText="Created At" />
                         <asp:CommandField ShowEditButton="True" ShowDeleteButton="True" HeaderText="Actions" />
</Columns>

            </asp:GridView>
        </div>
        
        <div class="category-card">
            <div class="category-header">
                <h2>Expense Tracker</h2>
                <p class="mb-0">Add a new expense category</p>
            </div>
            <div class="form-floating">
                <asp:Label ID="lnm" runat="server" Text="Name" CssClass="form-label"></asp:Label>
                <asp:TextBox ID="nm" runat="server" CssClass="form-control"></asp:TextBox>
                <asp:Button ID="add" runat="server" Text="Add" OnClick="Add_Category" CssClass="btn-add" />
                <asp:Label ID="show" runat="server"></asp:Label>
            </div>
        </div>
    </div>
    
    <div class="container"></div>
</asp:Content>

